// Explicitly labelled demonstration data. Never accepted by the real cart API.
export const sampleCatalog = [
  {
    _id: "sample-paint-1",
    name: "Sample warm-white paint · 1 L",
    sku: "DEMO-P1",
    unit: "piece",
    sellingPrice: 260,
    scanSpace: {
      enabled: true,
      materialType: "paint",
      color: "#eee8dd",
      variantGroup: "sample-white",
      coveragePerLiter: 10,
      packageVolume: 1,
      recommendedCoats: 2,
    },
  },
  {
    _id: "sample-paint-5",
    name: "Sample warm-white paint · 5 L",
    sku: "DEMO-P5",
    unit: "piece",
    sellingPrice: 1050,
    scanSpace: {
      enabled: true,
      materialType: "paint",
      color: "#eee8dd",
      variantGroup: "sample-white",
      coveragePerLiter: 10,
      packageVolume: 5,
      recommendedCoats: 2,
    },
  },
  {
    _id: "sample-sage",
    name: "Sample sage paint · 4 L",
    sku: "DEMO-S4",
    unit: "piece",
    sellingPrice: 980,
    scanSpace: {
      enabled: true,
      materialType: "paint",
      color: "#a0afa4",
      coveragePerLiter: 10,
      packageVolume: 4,
      recommendedCoats: 2,
    },
  },
  {
    _id: "sample-floor",
    name: "Sample oak flooring · 2.2 m²",
    sku: "DEMO-F1",
    unit: "box",
    sellingPrice: 1600,
    scanSpace: {
      enabled: true,
      materialType: "wood",
      color: "#b99d7a",
      coveragePerPack: 2.2,
      tileSize: 0.22,
    },
  },
  {
    _id: "sample-tile",
    name: "Sample stone tile · 1.44 m²",
    sku: "DEMO-T1",
    unit: "box",
    sellingPrice: 720,
    scanSpace: {
      enabled: true,
      materialType: "tile",
      color: "#c5c7c2",
      coveragePerPack: 1.44,
      tileSize: 0.6,
    },
  },
  ...[
    ["sofa", "Sofa", 2.3, 0.85, 0.9, 12900],
    ["table", "Coffee table", 1.15, 0.42, 0.6, 2490],
    ["cabinet", "Sideboard", 1.5, 0.85, 0.45, 7200],
  ].map(([file, name, width, height, depth, price]) => ({
    _id: `sample-${file}`,
    name: `Sample ${name.toLowerCase()}`,
    sku: `DEMO-${file}`,
    unit: "piece",
    sellingPrice: price,
    scanSpace: {
      enabled: true,
      materialType: "object",
      glbModelUrl: `/scanspace/models/${file}.glb`,
      modelDimensions: { width, height, depth },
      color: "#b99872",
    },
  })),
];
export const sampleInventory = sampleCatalog.map((p) => ({
  product: p._id,
  quantity: 200,
  reservedQuantity: 0,
}));
